# Generated by Django 3.1.3 on 2020-11-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201129_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='uncatogorozed', max_length=200),
        ),
    ]
