# Generated by Django 3.1.3 on 2020-12-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201203_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_image',
        ),
    ]
